development:
  adapter: postgresql
  host: localhost
  database: swish_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  database: swish_test
  pool: 5
  timeout: 5000
